{"uuid":"ef9f84f8-8390-443e-af21-d85258412276","historyId":"ba9d5a52c380136a4ed6dc0533e92201","fullName":"Page_Test.Home_Page_Test.TC020_verify_SOS","labels":[{"name":"package","value":"Page_Test.Home_Page_Test"},{"name":"testClass","value":"Page_Test.Home_Page_Test"},{"name":"testMethod","value":"TC020_verify_SOS"},{"name":"parentSuite","value":"Hero_App"},{"name":"suite","value":"Home_Page_Test"},{"name":"subSuite","value":"Page_Test.Home_Page_Test"},{"name":"host","value":"users-MacBook-Pro.local"},{"name":"thread","value":"4852@users-MacBook-Pro.local.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"TC020_verify_SOS","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Test interrupted: org.openqa.selenium.WebDriverException: Error occurred for request - /wd/hub/session/95c7c038-1248-466b-aa56-c3069435c433/element, error - dial tcp 10.151.0.133:5295: connect: connection refused\nBuild info: version: '4.8.1', revision: '8ebccac989'\nSystem info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '14.6.1', java.version: '22.0.1'\nDriver info: io.appium.java_client.ios.IOSDriver\nCommand: [95c7c038-1248-466b-aa56-c3069435c433, findElement {using=xpath, value=//XCUIElementTypeStaticText[contains(@name,'The app will alert with')]}]\nCapabilities {appium:autoAcceptAlerts: true, appium:automationName: XCUITest, appium:bundleID: com.customerapp.hero, appium:bundleId: com.customerapp.hero, appium:databaseEnabled: false, appium:derivedDataPath: /Users/ltadmin/Documents/ap..., appium:deviceName: iPhone 16, appium:headless: false, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:mode: cloud, appium:nativeWebScreenshot: true, appium:networkConnectionEnabled: false, appium:newCommandTimeout: 0, appium:noReset: false, appium:orientation: PORTRAIT, appium:platformVersion: 18.0, appium:takesScreenshot: true, appium:udid: 00008140-000954542E13001C, appium:uiautomator2ServerLaunchTimeout: 60000, appium:usePrebuiltWDA: true, appium:waitForQuiescence: false, appium:wdaLocalPort: 11174, appium:wdaStartupRetries: 3, appium:webStorageEnabled: false, appium:webkitResponseTimeout: 20000, platformName: IOS}\nSession ID: 95c7c038-1248-466b-aa56-c3069435c433","trace":"java.lang.AssertionError: Test interrupted: org.openqa.selenium.WebDriverException: Error occurred for request - /wd/hub/session/95c7c038-1248-466b-aa56-c3069435c433/element, error - dial tcp 10.151.0.133:5295: connect: connection refused\nBuild info: version: '4.8.1', revision: '8ebccac989'\nSystem info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '14.6.1', java.version: '22.0.1'\nDriver info: io.appium.java_client.ios.IOSDriver\nCommand: [95c7c038-1248-466b-aa56-c3069435c433, findElement {using=xpath, value=//XCUIElementTypeStaticText[contains(@name,'The app will alert with')]}]\nCapabilities {appium:autoAcceptAlerts: true, appium:automationName: XCUITest, appium:bundleID: com.customerapp.hero, appium:bundleId: com.customerapp.hero, appium:databaseEnabled: false, appium:derivedDataPath: /Users/ltadmin/Documents/ap..., appium:deviceName: iPhone 16, appium:headless: false, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:mode: cloud, appium:nativeWebScreenshot: true, appium:networkConnectionEnabled: false, appium:newCommandTimeout: 0, appium:noReset: false, appium:orientation: PORTRAIT, appium:platformVersion: 18.0, appium:takesScreenshot: true, appium:udid: 00008140-000954542E13001C, appium:uiautomator2ServerLaunchTimeout: 60000, appium:usePrebuiltWDA: true, appium:waitForQuiescence: false, appium:wdaLocalPort: 11174, appium:wdaStartupRetries: 3, appium:webStorageEnabled: false, appium:webkitResponseTimeout: 20000, platformName: IOS}\nSession ID: 95c7c038-1248-466b-aa56-c3069435c433\n\tat org.testng.Assert.fail(Assert.java:110)\n\tat Page_Test.Home_Page_Test.TC020_verify_SOS(Home_Page_Test.java:75)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:829)\n\tat org.testng.TestRunner.run(TestRunner.java:602)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:437)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:330)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1176)\n\tat org.testng.TestNG.runSuites(TestNG.java:1099)\n\tat org.testng.TestNG.run(TestNG.java:1067)\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)\n"},"stage":"finished","steps":[],"attachments":[{"name":"Error Log","source":"0e5e9a0d-e928-4bea-9b0b-85e2f1bdf8d8-attachment.txt","type":"text/plain"}],"parameters":[],"start":1733463708622,"stop":1733463728781}